name: Visual regression tests

on:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
    - cron:  '0 6 * * *'

env:
  THUNDER_ADMIN_TESTS_BRANCH: 'master'

jobs:
  visual:
    runs-on: ubuntu-latest
    container: cypress/included:9.2.0
    # cypress/browsers:node16.5.0-chrome94-ff93

    strategy:
      fail-fast: false
      matrix:
        browser: ['chrome', 'firefox']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        run: cypress run --browser ${matrix.browser}
