name: Visual regression tests

on:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
    - cron:  '0 6 * * *'

env:
  THUNDER_ADMIN_TESTS_BRANCH: 'master'

jobs:
  chrome:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.5.0-chrome94-ff93
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome

  firefox:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.5.0-chrome94-ff93
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: firefox
