name: Visual regression tests

on:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
    - cron:  '0 6 * * *'

jobs:
  visual:
    runs-on: ubuntu-20.04
    # container: cypress/included:9.2.0
    # cypress/browsers:node16.5.0-chrome94-ff93

    strategy:
      fail-fast: false
      matrix:
        browser: ['chrome', 'firefox']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Enable LFS
        run: |
          echo "cypress/snapshots/** filter=lfs diff=lfs merge=lfs -text" >.gitattributes
          git lfs pull
      - name: Install dependencies 📦
        uses: bahmutov/npm-install@v1
      - name: Cypress run
        run: docker run --env-file <(env) -v $PWD:/e2e -w /e2e cypress/included:9.2.1 -s cypress/integration/*.spec.js -b ${{matrix.browser}} -e updateSnapshots=true
        env:
          CYPRESS_BASE_URL: 'https://thunder-morpho.herokuapp.com'
#          updateSnapshots: true
      - name: Upload images artifact
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: images-${{matrix.browser}}
          path: cypress/snapshots
      - name: Check changes
        if: failure()
        run: git status
